apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: starry-night
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: rouaabenayed/shooting-stars:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
          volumeMounts:
            - name: dockerhub-credentials-volume
              mountPath: /etc/docker-credentials
              readOnly: true
      volumes:
        - name: dockerhub-credentials-volume
          secret:
            secretName: dockerhub-credentials # Use the Secret here for mounting
      imagePullSecrets:
        - name: dockerhub-credentials # Use the Secret here for image pulling
