apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: starry-night
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: rouaabenayed/shooting-stars:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
      imagePullSecrets:
        - name: dockerhub-credentials
