apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBqJEt3gQ8aLWRd89naeeyvyIKKJ9NXxPNz6sfQmuEzz7ICgMYNnq6c54JNW4Cqp3E85XZfSU1jSCZ/XYvoeJkNi8F5aBrO9APaAcNJhM6wp0A9mnw5Rh+xxg4vUHExRM2csv8r1YjSFCfr1d1sIKaAGlNG4N1zkcBKCo034bSMcEXxNLycPpo+SqiEcx4CJsqaOSmoOVS2UsBvwoJsLngNA8RzGnsmSOXgiB5ZgLgBmPyanO1sxpQZ9HGb6e6Qpk8CXUy4/XzkTRaFkLsJF5T/mYWvISS9ZvYHS2zn57johwATgT3aj1FciwIfbKD1oW/l3Y1tA5901l7tCy3w5sOg+xuEo+jlcxpRgq0rO1tezBgF8o1MX8WRQ80r3UYbLrc+kG8aFOIj3O/i1qtYtcHZLMiUpXHKxGWFfYUvGmPG00GJ40P+E/t3dGgBLzR1iRjh8Ck+VIB9RHO4i7VfN0DCKlZaYvtvKUAWdIPu3Tw0WXPSZQFHmzRMFMScIw9IB1Uv/pQu4Q5R+N/8RxDtJ7GYyMP1THWsUK8LkU3fEGlnQyADcwggErWC+iV41Bm2hJbOoCSvrstXI6xPP5X2WjDgDY0FZtuXfPyKvdCKaGwI1uXsslBY+DLfdtcSBl4aW5KzSgJiMMLgi5fzdnOYqjbc+kTBnzoGWl0wfwqr6ys5b6WPc7GYImVLhVSCv3nYk1H7dAoJcXAFMBaOhRxsowIzhdZbg35AUlC/UrBi5V/WYuGTVj5uiV/39BKVg620LQmOD8ZRIODDjwhxdmIESws++iOJB2Coys7mahhM27FSNKTnHtBDhdJKAy8HU6p2xqMtOQtyCfX6tI2Ssh7dkZm4pQUpYJSlYE73g3hwE9+iBBVxGMqdG66Z+MFZwQ5UrD5tlc+R
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
