apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgACGkLGHM8/1dcUdNKA07SLtwXOORu1+v4k0H0U4vjY8lO4EwcIzuNYFPTvtW6teixnF1z0kKNtw3SDMRG3wDj+jMUa88EFdeZpH8FBn5iLGXyEna3GD6U76mzdg+qvMPR74H3dtvAWkLLp3lRZmRuWx/x0o2JN3NVxyHuI+1YZXA8exKKCGXTBqDXlCZMaHlmdc1ax4Fl0J+I+7Al3MFb+SWP63+EjXlUgJD/1ATi6Erhuc0MuBSb7WuohOQcyPjPdcK2x4CaZG/jF+e7px0/Rrv2KJLvc3UmyUttIVQovSJQ3pbogf3CO9XXM27QE+Qu/aiaGDm8b7El4cxYISmJ2Y9w7DuRzCSGzWuY+tfa3piKyjS01hlLJvvrgU1dqGc/eTwDPBSi6kLXxahuAdfGOabs1NR3uiGaghAbpB20mo7Axe9S6ZJrUcfAkUknAXJsBuFlDxuoWnsyDU6mLM0TKG9/qyp0ff3q6o/xvDZ7f1cI1q9XtPYXO8FpSoOdjzxEVkBb4uQZ/rzoFnPq7iLZnE3RwyBwSSQQhA0GXRdzkN4poKgsDyxsYBtIWGi09HIPBPjr2OXOjXFuYqe/nOQ8Z3aBF8M7JN6FztdmeSkvHgd74bwEqbqWCXirXp09MTQUiNLQSiSZhwZF6L2s62xyQ31U3yXTVJkHijP6+/fiVtMH8Tdn85D0yY+ng2RcxTMUrvDNPQjp83xAgGV464Epgt3Jxmd0t3tkOw/jMbVtV3aRSXURpGqJ0EMf+UUJtQIp+dnWHrpwcJgIonEMgjHfGcpYLjZdAIEcaafPYXkvHn6vF6199YEoqQ1TSWxF3RIH90sgyuee5n7wjQ8QlanuFbkNQ5L4jvHLI3PdvB5S1t5uYjNFfOEcvVDVnBmst91vZnrqv
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
