apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAcFg5vij2XsnujxDLX16kT6zs6N32DN2lQL3IhWj2as1Am2CoxXKCsFbn4qkUChE5VwedGoTrOqJEqLcFj2XWlFmWPMQ6zrQgVOjaTKpyswzgFUTdLa6ktZwPzOXrjC8SMp/ykYUz71lpM8wvrxtF38Ow48cjkiRz513W0h52PGcuzadOAKcdRFC7PPBdVCz2XMUL7omDZ4NLKY+yQP16K4XX3UrNdowX4qe5Y81Vjvyeox4FH+cCRs+bpfv1LabzbVxg6MMJXHep+vLbnfZ1u/XXWhno9r1/H6/eKoTHlSEzouCHzg9E+QLpjncJfwCMy1Q7/HWnGz5cfWRBg61dXdx3y3ZSffxSqWancSujv0fu05M9mI4RgSB8ABNbEV0G1U7MY3vDyKyf6uPFvrGtnc4ItaC2O1/PgPKPvpm2bbsvQ116/GDZhSzP/HyOxLN3KaoF1OyhHTL8h0JSeFJFoVkAx6qf06MMVQ9zLL4qNieCFRaPPNqHzXIaUQ3j89unFEREn1888SiDV0JP6t+nkpUU4HWC+vBkR9uPXyUfROiqBOTyW4iSgStyuUhJaXilPg5ScBKVmHQwLHn/AkDtk/6RVj4hJKPb+eb9zjsgoPTZEX0NJ6iDB9vuYivMbA4cMiMF2KEbyrBGdCXlG2eVb1TXFbT4qPZXfEppMHlxgX8dR8SIsLvPLAV40SBWpWWSemgsPEWBc28ac4G03irIj4WM33I9o+S2APZPiEa4aCNMhNlNxGM8YAX2Uzl1XPxJrr69/MN6nWEqRonYcQ73Ku6GpHn4FjaljuhEq5Zhj/NXwxiGTuRNs6Z+EX/wFzMxUpnPMaXboCajsQSJxWs+QGxsiZI+fhkRUTMcmffDRSH0+RCnGa/tJKzNdknNG5OGMkuyZ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
